### ISSUE TITLE
missing Dependency libmemcached.so.5()(64bit)

### ISSUE THREAD

**Issue by abrutus** [tag1consulting/hphp#4]
It all seems to be working ok with the `yum install hiphop-php` until the very end

```

hiphop-php-1.1-1.el5.x86_64 from hphp has depsolving problems
  --> Missing Dependency: libmemcached.so.5()(64bit) is needed by package hiphop-php-1.1-1.el5.x86_64 (hphp)
Error: Missing Dependency: libmemcached.so.5()(64bit) is needed by package hiphop-php-1.1-1.el5.x86_64 (hphp)
 You could try using --skip-broken to work around the problem
 You could try running: package-cleanup --problems
                        package-cleanup --dupes
                        rpm -Va --nofiles --nodigest

```

I appear to have memcached
`Package libmemcached-1.0.9-2.x86_64 already installed and latest version`

**Comment by jeffsheltren** [comment]
The problem is that libmemcached.so.5 is provided by the libmemcached package in the hphp repo. Since you already have a newer version of libmemcached installed (which does not provide that file), yum won't install the other version.  Where was your libmemcached installed from?  I see that EPEL only has libmemcached-0.31-1.1.el5.x86_64 -- which is likely why a newer one was included in the hphp repo.

**Comment by abrutus** [comment]
Makes sense,
Do you know how I would tell it to install that specific version after I do `yum remove libmemcached` ? That'd be helpful
Thanks

**Comment by jeffsheltren** [comment]
There are various ways to exclude a package and/or repository in yum.  One way is to add an 'excludes=libmemcached' line to the repo configuration for the repo that you got it from initially.

**Comment by abrutus** [comment]
For the record, I just went on /etc/yum.d/ and removed all the external repos that I had used for other purposes other than hiphop, ran a `yum update` , `yum remove libmemcach*` and tried installing again.. and It appears to be working.
